# Generated by Django 4.2 on 2023-04-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
