# Generated by Django 4.2 on 2023-05-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='completed',
        ),
    ]
